### ISSUE TITLE
Rows removed when cannot set lines

### ISSUE THREAD

**Issue by BenHall** [sourcelair/xterm.js#424] opened 2016-12-22 21:17 UTC
I'm not sure why, but we're seeing this error:

```
Uncaught TypeError: Cannot set property '0' of undefined
    at Terminal.write (term.js:188)
    at Socket.<anonymous> (terminal-application.js:18)
    at Socket.Emitter.emit (socket.io.js:35)
    at Socket.onevent (socket.io.js:16)
    at Socket.onpacket (socket.io.js:15)
    at Manager.<anonymous> (socket.io.js:29)
    at Manager.Emitter.emit (socket.io.js:35)
    at Manager.ondecoded (socket.io.js:8)
    at Decoder.<anonymous> (socket.io.js:29)
    at Decoder.Emitter.emit (socket.io.js:35)
term.js:133 Uncaught TypeError: Cannot read property '0' of undefined
    at Terminal.refresh (term.js:133)
    at term.js:126
term.js:129 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Terminal.refresh (https://katacoda.com/javascripts/term.js:129:185)
    at https://katacoda.com/javascripts/term.js:126:33
term.js:129 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Terminal.refresh (https://katacoda.com/javascripts/term.js:129:185)
    at https://katacoda.com/javascripts/term.js:126:33
term.js:129 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Terminal.refresh (https://katacoda.com/javascripts/term.js:129:185)
    at https://katacoda.com/javascripts/term.js:126:33
term.js:129 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Terminal.refresh (https://katacoda.com/javascripts/term.js:129:185)
    at https://katacoda.com/javascripts/term.js:126:33
```

When it happens, the xterm rows are removed.

![screenshot 2016-12-22 21 12 43](https://cloud.githubusercontent.com/assets/82614/21440639/d400f2ce-c88b-11e6-9e1d-e648372403eb.png)

**Comment by Tyriar** [comment] 2016-12-23 10:09
I believe this is a duplicate of https://github.com/sourcelair/xterm.js/issues/385

**Closed** 2016-12-29 11:56 UTC
