### ISSUE TITLE
How can xterm integrate with react component?

### ISSUE THREAD

**Issue by zhaoyi0113** [sourcelair/xterm.js#859] opened 2017-08-07 04:59 UTC
I am using reactjs as frontend framework. After read some demos from `xterm`, I found I have to attach a dom to xterm object in order for rendering. But for reactjs, it has its own rendering method. How can I make xterm to render in react component? How does these two libraries integrate with each other?

**Comment by Tyriar** [comment] 2017-08-07 05:58
Duplicate of https://github.com/sourcelair/xterm.js/issues/260

**Closed by Tyriar** 2017-08-07 05:58 UTC
