### ISSUE TITLE
Bug in resize/fit

### ISSUE THREAD

**Issue by ioquatix** [sourcelair/xterm.js#875] opened 2017-08-09 03:02 UTC
In some cases xterm fails because an off by n error in the render function.

## Details
- Browser and browser version: Atom 1.19.0 / Electron
- OS version: Mac OS X 10.12.6
- xterm.js version: 2.9.1

### Steps to reproduce

1. Create the terminal of size `rows: 40 cols: 80`
2. Immediately call fit which makes it bigger, e.g. `{terminal: Terminal, cols: 82, rows: 45}`
3. Crash in Render.

```
      for (let i = 0; i < width; i++) { // i = 80, width = 82, lines has 80 things in it.
        // TODO: Could data be a more specific type?
        let data: any = line[i][0]; // lines[80] is undefined.
```

**Comment by ioquatix** [comment] 2017-08-09 03:05
A quick hack to work around this is to make sure the initial size is always bigger than the first resize:

```
    @term = new Terminal {
      rows: 400
      cols: 800
      scrollback: atom.config.get('script-runner.scrollback'),
      useStyle: no
      screenKeys: no
      handler: (data) =>
        @emitter.emit('data', data)
      cursorBlink: yes
    }
```

Seems like a massive hack though.

**Comment by ioquatix** [comment] 2017-08-09 03:23
The problem is reproducible with this branch:

https://github.com/ioquatix/script-runner/commit/494399261ae7a08d438c72a7f7c3b5d4e9411d2c#diff-ff2e3d1abc5ef3094441fd3d980abbe4R95

**Comment by ioquatix** [comment] 2017-08-09 03:24
(but you need to change `cols: 80 * 4` to `cols: 1` to crash every time).

Once the terminal is working/displaying/refreshing correctly, calling resize works as expected.

**Comment by Tyriar** [comment] 2017-08-09 06:49
Duplicate of https://github.com/sourcelair/xterm.js/issues/860, it's already fixed in master. Hopefully a release should come soon 😃

**Closed by Tyriar** 2017-08-09 06:49 UTC

**Comment by ioquatix** [comment] 2017-08-09 08:08
Cool can you let me know when it's released? Thanks :)

**Comment by parisk** [comment] 2017-08-09 08:39
It is: https://github.com/sourcelair/xterm.js/releases/tag/2.9.2 😄
