### ISSUE TITLE
clear() is not correctly clearing the buffers

### ISSUE THREAD

**Issue by twifty** [sourcelair/xterm.js#943] opened 2017-09-04 19:36 UTC
As you may know there is currently a problem with `node-pty` having a race condition between its 'data' and 'exit' events. Sometimes, under a linux environment, an 'exit' will be emitted before all the data buffers have been flushed. While sending these data buffers into `xterm` it's possible for the final `write` to contain an unfinished ANSI sequence.

An example of an unfinished write:

>  [33mgenerate[39m
>   [32mgenerate:bundle[39m                         Generates a bundle
>   [32mgenerate:command[39m                        Generates a console command
>   [32mgenerate:controller

When calling `clear` after such data I would expect all buffers to be emptied. This is not the case. The next call to `write` will prefix the first line with the unfinished final line of the previous `write`.

To reproduce:

1. `write` the above, incomplete, data string.
2. call `clear`
3. `write` any new data string. ("Hello World" for example)

You will see the new terminal contents contain

> generate:controllerello World

**Comment by Tyriar** [comment] 2017-09-04 19:45
Duplicate https://github.com/Tyriar/node-pty/issues/72

**Comment by twifty** [comment] 2017-09-04 20:05
This is not a duplicate. It is caused by that issue, but the input could very come from a different source.

The fact is, `clear` should empty all internal buffers, it doesn't. remnants of incomplete writes are prepended even after the call to `clear`.

**Comment by Tyriar** [comment] 2017-09-05 04:07
My mistake. Re-reading this, I think your saying that parser state should be cleared when you so a clear, but I'm not so sure about that. Isn't the typical case where this would occur be to clear when data is streaming in, in which case you really want the parser to know about the partial escape sequence state, otherwise it would print the escape sequence to the terminal.

I think your actually after `Terminal.reset()` which does a hard reset of the terminal.

**Comment by twifty** [comment] 2017-09-05 11:36
From what I understand, clear or <ESC>c, should empty the screen and all scrollback buffers. Other setting, like 'font' and 'line wrap' should remain intact.

In the example "<ESC>[32mgenerate:controller<ESC>", the <ESC>32mgenerate:controller" should print "generate:controller" with a green text. This should then become part of the history and should be cleared and forgotten. Though it's state should be switched to use green text.

The next, incomplete "<ESC>", is what is causing the problem. At this point the terminal has no idea what this sequence should be. A call to `clear` should detect this and treat it as an invalid character (think of it as an incomplete utf8 byte sequence or an unprintable char code for example).

If you think about it, streaming data to the terminal will happen in a loop. How often do you clear the terminal during a stream? Usually the clear would be the result of another event, waiting for stdin for example, in which case we can be sure incomplete escape sequences will not exist. Any other calls to clear require a certain level of care, for example detect a new line char and clear everything before it. This burden is imposed on the end developer though.

Another way to think of this, since '<ESC>[2J' also clears the buffers, what should '<ESC><ESC>[2J' do?

**Comment by jerch** [comment] 2017-09-05 12:47
@twifty There are several problems you mentioned that should not been mixed up:

* **node-pty**: The 'data' & 'exit' problem is a misunderstanding of the events. The 'exit' event is coupled to the exit of the process with its exit code and _not the end of stream data_. If you read the `child_process` doc carefully you will find the same difference for 'exit' and 'close'. `node-pty` tries to circumvent this by holding the 'exit' event back until the stream dies. This works properly on linux & OSX and has some problems on Windows. The much bigger problem with `node-pty`'s current implementation is an early end of stream with losing data that already got written to the pipe buffer if the child process finishes very early. Thats currently under investigation.

* **clear `node-pty` buffers**: Since terminal data is consecutive it is never a good idea to do this as you already know. Dont delete stuff in the middle of a running session. Imagine the slave process started a DCS call, but you misses the introducer because of the clear - hell will break loose.

* **terminal parser and remnant escape sequences**: Should not happen in the first place (see above), but sometimes sequences are malformed or bytes dropped for whatever reason. The spec makes clear what to do if the parser does not understand the bytes - degrade to the initial state - which means print whatever follows until the next escape sequence.

* **clear terminal content**: Thats the right place to "forget" stuff. All data got read and parsed, the terminal is (hopfully) in a sane state - from here on you can delete characters, lines, history, whatever.

**Comment by twifty** [comment] 2017-09-05 14:05
Just to be clear, when I mention `clear` above, I'm talking about the `xterm` class method not `node-pty`. Clearing the upstream buffers is not something I would do without good reason.

The current problem with `xterm.clear()` isn't limited to the incomplete escape sequence. These are the final 3 lines recieved from `node-pty` before it's `exit` event:

>  [33mgenerate[39m
>   [32mgenerate:bundle[39m                         Generates a bundle
>   [32mgenerate:command[39m                        Generates a console com

These lines are rendered with `xterm.write()`. Running `xterm.clear()` now, does clear the rendered contents leaving the displayed terminal completely empty. Granted `xterm.reset()` would be better suited, but this is how I discovered this bug.

Calling `xterm.write()` again, on a cleared terminal, prefixes the first line.

So, first line returned from a *fresh* `node-pty`  `data` event:
> Symfony [32m3.2.13[39m (kernel: [33mapp[39m, env: [33mdev[39m, debug: [33mtrue[39m)

But, `xterm` actually renders:
> [32mgenerate:command[39m                        Generates a console comSymfony [32m3.2.13[39m (kernel: [33mapp[39m, env: [33mdev[39m, debug: [33mtrue[39m)

**Comment by jerch** [comment] 2017-09-05 14:28
Ok  gotcha, there is something stuck in the terminal buffers.

**Comment by Tyriar** [comment] 2017-09-05 18:25
I'm not sure this is a bug though, clear is essentially cmd+k on macOS terminals. We don't want to flush the parser state as then doing clear while output is streaming would result in the end of an escape sequence being output.

**Comment by jerch** [comment] 2017-09-05 19:04
@Tyriar As far as I understand it the following chars get rendered twice (before and after the clear), but were only once in the input stream:
> �[32mgenerate:command�[39m Generates a console com

**Comment by twifty** [comment] 2017-09-05 19:05
@Tyriar The example I gave above certainly is a bug. The terminal should not render the same content multiple times. This string "�[32mgenerate:command�[39m Generates a console com" was already rendered once before the `clear`. This particular string doesn't end in the middle of an escape sequence, so the parsers state should not be affected. Calling the `clear` method, which should be functionally the same as writing `\<ESC\>[2J`, should remove all the rendered text from the terminal and empty the scrollback buffers.

The problem is, this isn't being done. The terminal is holding the final line and for some reason rendering it again before the next string input.

**Comment by twifty** [comment] 2017-09-05 19:11
The example in my opening thread is different in that it ends in the middle of an escape sequence. IMO, sending a `<ESC>[2J` at this point should drop the previous opening `<ESC>`.

The chances of entering new data in the middle of an escape sequence, while streaming data, are remote. Even then it would require two writers to the same terminal. How the parser handles such a situation is not the problem here.

**Comment by Tyriar** [comment] 2017-09-06 02:37
> The problem is, this isn't being done. The terminal is holding the final line and for some reason rendering it again before the next string input.

This is as designed. When the terminal is filled:

![image](https://user-images.githubusercontent.com/2193314/30091811-76642d3e-9270-11e7-9e3f-ca117af1d01d.png)

Calling `clear` should retain the prompt line:

![image](https://user-images.githubusercontent.com/2193314/30091858-a652ce60-9270-11e7-8b9c-039209dc1836.png)

For it to come out like this would be a bug given [the definition the API](https://xtermjs.org/docs/api/terminal/#clear)
 provided in the API docs:

![image](https://user-images.githubusercontent.com/2193314/30091882-d0cdf57a-9270-11e7-8e85-152641f29b21.png)

Again, I think you want [`Terminal.reset`](https://xtermjs.org/docs/api/terminal/#reset), or something else that we don't support right now.

**Comment by twifty** [comment] 2017-09-06 02:52
@Tyriar My terminal doesn't have a command prompt. Previously written lines of **text** are being written to the console **again**, after the clear. This is most definite a bug.

Here is an over simplified example:
1. `Terminal.write("Hello World")`  Terminal displays "Hello World"
2. `Terminal.clear()` Terminal is empty
3. `Terminal.write("foo")` Terminal displays "Hello Worldfoo"

Can you see? It has rendered "Hello World" for a second time.

**Comment by Tyriar** [comment] 2017-09-06 03:58
@twifty of course I understand not all processes are shells, this is what clear was defined for though; it's working exactly as described in the documentation.

This should work around your problem if you don't want to use `reset()`:

```js
// Partial escape
term.write('\x1b')
// First \n will cancel any existing escape or go to new line
// Then the \n\r will put the cursor at the start of the next line
term.write('\n\n\r')
term.clear()
```

I don't feel like there's sufficient need to expose new API for this so I'll close it off.

**Closed by Tyriar** 2017-09-06 03:58 UTC
Labels: need more info
