### ISSUE TITLE
Demo index.html doesn't appears working in IE11 Windows 7

### ISSUE THREAD

**Issue by goflatworld** [sourcelair/xterm.js#317] opened 2016-10-21 23:29 UTC
## Details
- Browser and browser version: IE 11.0
- OS version: Windows 7
- xterm.js version: The current version (downloaded from this website)
### Steps to reproduce

 I just downloaded terminal.js. I didn't run npm install and npm start. All I did was 
1. Edit demo/index.html, change the xterm.js source to be ../dist/xterm.js
2. dobule click index.html and it opened in web browser. (tired ,firefox, chrome, IE. Also tried Linux, Windows 7 and MAC)
3. The terminal area is small, I can only type ONE character at a time. It also only shows one character "W" below the box.

I'm new to xterm.js. I want to use it as a client only XTERM. I have written my own Websocket server. I thought that for a javascript, all I need to do is download them and include it in my html and I should be  good to go... Maybe I have missed something obvious?

**Comment by Tyriar** [comment] 2016-10-21 23:38
You need to `npm install` to run the demo, however I'm not sure it's currently working on Windows.

**Comment by goflatworld** [comment] 2016-10-22 00:11
I'm on Ubuntu Linux 16 now. I have run "npm install" and when I try "npm start", I got below errors. 

/xterm.js$ npm start

> xterm@2.0.1 /xterm.js
> nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! xterm@2.0.1 start: `nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the xterm@2.0.1 start script 'nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /xterm.js/npm-debug.log

**Comment by goflatworld** [comment] 2016-10-22 00:13
Below is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle xterm@2.0.1~prestart: xterm@2.0.1
6 silly lifecycle xterm@2.0.1~prestart: no script for prestart, continuing
7 info lifecycle xterm@2.0.1~start: xterm@2.0.1
8 verbose lifecycle xterm@2.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle xterm@2.0.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/flatworld/workspace/Stingray/V2/beast/xterm.js/node_modules/.bin:/home/flatworld/bin:/home/flatworld/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle xterm@2.0.1~start: CWD: /home/flatworld/workspace/Stingray/V2/beast/xterm.js
11 silly lifecycle xterm@2.0.1~start: Args: [ '-c',
11 silly lifecycle   'nodemon --watch src --watch addons --exec bash -c \'./bin/build && node demo/app\'' ]
12 info lifecycle xterm@2.0.1~start: Failed to exec start script
13 verbose stack Error: xterm@2.0.1 start: `nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid xterm@2.0.1
15 verbose cwd /home/flatworld/workspace/Stingray/V2/beast/xterm.js
16 error Linux 4.4.0-38-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error xterm@2.0.1 start: `nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'`
24 error spawn ENOENT
25 error Failed at the xterm@2.0.1 start script 'nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app''.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the xterm package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs xterm
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls xterm
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by goflatworld** [comment] 2016-10-22 02:42
Appears that I need install the legacy node. So I installed it via "sudo apt-get install nodejs-legacy". After that. I got below error when I run "npm start"

> xterm@2.0.1 start xterm.js
> nodemon --watch src --watch addons --exec bash -c './bin/build && node demo/app'

[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: xterm.js/src/**/* xterm.js/addons/**/*
[nodemon] starting `bash -c "./bin/build && node demo/app"`
Building xterm.js into build
  - Building build/xterm.js...
[BABEL] Note: The code generator has deoptimised the styling of "xterm.js/src/xterm.js" as it exceeds the max of "100KB".
    OK.
  - Building build/xterm.css...
    OK.
module.js:328
    throw err;
    ^

Error: Cannot find module 'pty.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (xterm.js/demo/app.js:5:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by parisk** [comment] 2016-10-23 10:02
@goflatworld the reason this did not work on your Windows machine is that the file was not served by `app.js`, which is the demo server.

You can find instructions on how to run the demo appropriately in the README (https://github.com/sourcelair/xterm.js#demo):

> To launch the demo simply run:
```
npm install
npm start
```
Then open http://0.0.0.0:3000 in a web browser (use http://127.0.0.1:3000 if running under Windows).

This requires you to have `node` pre-installed on your machine.

Now, considering your issues on Linux the problem is that you have Node.js installed as a `nodejs` binary and not as `node`.

This can easily be fixed by running `sudo ln -s $(which nodejs) /usr/local/bin/node`.

**Comment by goflatworld** [comment] 2016-10-24 08:55
Thanks.

I have managed to get my own code working. Now I'm trying to dive bit deep into it.

**Comment by parisk** [comment] 2016-10-24 09:09
👍 . Should we close this issue then?

**Closed** 2016-11-04 12:52 UTC
