### ISSUE TITLE
zsh / oh-my-zsh - no scroll

### ISSUE THREAD

**Issue by wallverb** [sourcelair/xterm.js#151] opened 2016-06-28 14:37 UTC
If i start demo with `zsh` instead of `bash` and have `oh-my-zsh` installed then the scroll will not work in xterm.js

I am not sure if this is an issue with `xterm.js` or `oh-my-zsh`

The command that causes scroll to stop working is this command: `echoti smkx` that is located in `.oh-my-zsh/lib/key-bindings.zsh`

One can also start `xterm.js` without `oh-my-zsh` and type that command into terminal and it will stop scrolling.

**Comment by parisk** [comment] 2016-06-29 22:40
Thanks for reporting @wallverb. I do not have access to zsh right now, so I am not able to test this out.

Could you please take a look at your console in the developer tools of your browser and provide us with any errors/logs that might appear when attempting to scroll when in zsh with oh-my-zsh?

**Comment by wallverb** [comment] 2016-06-30 01:54
@parisk - when zsh/oh-my-zsh is executing that `echoti smkx` command then the following data is being sent to   `Terminal.prototype.write = function(data) `:

```
[?1l>
xterm.js:1467 


xterm.js:1467 ]2;echoti smkx
xterm.js:1467 ]1;echoti[?1h=[1m[7m%[m[1m[m    
```

which seems like that `=` char is causing this:

```
 // ESC = Application Keypad (DECPAM).
              case '=':
                this.log('Serial port requested application keypad.');
                this.applicationKeypad = true;
                this.state = normal;
                break;
```

and then ` this.applicationKeypad = true;` is causing return in scroll code:

```
      on(el, wheelEvent, function(ev) {
        if (self.mouseEvents) return;
        if (self.applicationKeypad) return;
```

**Comment by richarddavenport** [comment] 2016-07-08 14:44
@parisk, any movement on fixing this? Really appreciate the work!

**Comment by parisk** [comment] 2016-07-08 22:31
@richarddavenport unfortunately I didn't have time to deal with this and I do not project to be able to do so by the end of the month.

It would be extremely helpful if we could get an external contribution on this and I can definitely help anyone out with figuring out the internals of xterm.js.

**Comment by richarddavenport** [comment] 2016-07-11 13:44
@parisk I'd love to help! Is there any documentation anywhere, or could you help me get going with debugging? Is there an editor or IDE that works best? VS Code/Webstorm/Chrome Dev Tools? Thanks!

**Comment by Tyriar** [comment] 2016-07-11 16:45
@richarddavenport any editor works well. All the code is in [`./src/xterm.js`](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js) and instructions to run the demo are [here](https://github.com/sourcelair/xterm.js#demo).

**Comment by parisk** [comment] 2016-07-11 17:44
@Tyriar is right. Any editor supporting JavaScript works, so feel free to choose the one that suits you better.

Personal opinion though would be choosing an editor or IDE that uses xterm.js itself though, in order to dogfood it as well (use xterm.js when developing xterm.js). The two solutions that I am aware of right now are:

- [SourceLair](https://www.sourcelair.com/) that works completely in the browser; just visit https://lair.io/sourcelair/xterm and follow the instructions
- [Visual Studio Code](https://code.visualstudio.com/), just download it, clone the repo, run `npm install` and you are all set

Debugging with Chrome/Firefox DevTools is the best way to go IMO.

Considering the documentation, there is no public website at the moment but you should expect it within the week. Till that time just run `npm run build:docs` in your terminal and then you will be able to browse the API reference in HTML format, inside the `docs` directory.

Feel free to ask for more help in case the above do not suffice.

**Comment by parisk** [comment] 2016-07-11 22:52
@richarddavenport I published a preview version of the docs website, which contains the API reference. Most public methods are documented.

You can take a look at http://docs.xtermjs.org/. Hope it helps 😊 .

**Comment by richarddavenport** [comment] 2016-07-12 15:27
Wow! That's pretty awesome! @wallverb is right about the `echoti smkx` command in `oh my zsh`. That command is putting the terminal in Application Mode, which (I'm guessing here) is related to the `applicationKeypad` property. Does that sound right? I have no idea what application mode is, but it sounds important. [Line 1144](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L1144), if commented out, everything works, but I'm unsure of the consequences or what that line is there for. Do you know what that is for?

**Comment by Tyriar** [comment] 2016-07-12 18:45
Yes I'm a bit hesitant to touch it as I don't know what it does either.

[This reference doc](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html) we use mentioned it here:

> The application keypad transmits the following escape sequences depend-
ing on the mode specified via the DECKPNM and DECKPAM escape sequences.
Use the NumLock key to override the application mode.

The code also mentions:

```ts
              // ESC = Application Keypad (DECPAM).
              case '=':
                this.log('Serial port requested application keypad.');
                this.applicationKeypad = true;
                this.state = normal;
                break;

              // ESC > Normal Keypad (DECPNM).
              case '>':
                this.log('Switching back to normal keypad.');
                this.applicationKeypad = false;
                this.state = normal;
                break;
```

Looking into what DECPAM and DECPNM will likely lead us to an answer.

**Comment by richarddavenport** [comment] 2016-07-15 15:39
Xterm.js scrolling with oh my zsh now works, with [this branch](https://github.com/apjanke/oh-my-zsh/tree/ditch-smkx)

**Comment by apjanke** [comment] 2016-07-17 18:55
Hi. Found this thread from the related bug on Oh My Zsh.

> Looking into what DECPAM and DECPNM will likely lead us to an answer. Also if there's a difference with DECKPAM and DECKPNM.

I think DECPAM and DECPNM are just typos for DECKPAM and DECKPNM. The mnemonics are "DEC KeyPad Application Mode" and "DEC KeyPad Normal Mode".

Application keypad modes change what character sequences the cursor keypad and/or numeric keypad keys send in response to key presses. There are two (or more) distinct keypad modes which can be set to either "application" or "normal": the numeric keypad and the cursor keypad. The `applicationKeypad` and `applicationCursor` properties [modify the sequences sent by some keys](https://github.com/sourcelair/xterm.js/blob/13644ce35190e5bb5119e322f5f5f169ab7a1aa9/src/xterm.js#L2646-L2695), which seems appropriate.

It seems to me there may be a bug with the Home and End keys, though. Their behavior is [modified by the `applicationKeypad` property](https://github.com/sourcelair/xterm.js/blob/13644ce35190e5bb5119e322f5f5f169ab7a1aa9/src/xterm.js#L2680-L2695). But xterm considers Home and End to be cursor keys, controlled by DECCKM instead of DECKPAM/DECKPNM. (See the ["PC-Style Function Keys" section in that xterm reference document](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys).) I think that means they should be controlled by `applicationCursor` instead of `applicationKeypad`.
 
Regardless, it's surprising to me that the keypad mode would affect mouse scroll wheel behavior. (That's the scrolling that OP is talking, about, right?) Maybe the fix is as simple as removing that `if (self.applicationKeypad) return;` check from the mouse scroll wheel handler.

> I do not have access to zsh right now, so I am not able to test this out.

You can test this behavior under `bash` or other shells by doing `tput smkx`. That's equivalent to zsh's `echoti`. But be aware that under most terminfo definitions, `smkx` sends the sequences for both application cursor keypad and application numeric keypad modes, so you're not testing them independently if you do it that way. To test them independently (e.g. if you wanted to check which mode was controlling the Home/End behavior), you'd need to echo those escape sequences separately. (I don't remember how to do so off the top of my head.)

**Comment by Tyriar** [comment] 2016-07-19 17:26
I believe this is the same root cause as why scrolling doesn't work in vim which also sets `DECKPAM`.

**Comment by jerch** [comment] 2016-07-19 18:08
Following xterm's [mouse spec](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking) the mouse actions dont't get modified by DECKPAM or DECKPNM. Does anyone know why we have the `if (self.applicationKeypad) return;` in the mouse scroll handler at all?

**Comment by Tyriar** [comment] 2016-07-19 18:14
@jerch yeah I'm beginning to think that too, there's a bunch of reading I want to do in #194 to finally fix these sorts of issues.

**Comment by parisk** [comment] 2016-07-20 09:03
I think I have some more input to provide here.

> Maybe the fix is as simple as removing that if (self.applicationKeypad) return; check from the mouse scroll wheel handler.
@apjanke this won't work and should not work actually. This particular event handler is there to allow scrolling in simple text mode applications like bash, which have `applicationKeypad` set to `false` (btw. sounds quite helpful to document this better).

In addition, even if we removed this it would result in a `term.scrollDisp(1)` call, which would do nothing  when an app like vim is open, where `term.ydisp` and `term.ybase` are both 0.

This should be most probably handled in the previous event handler.

@richarddavenport did this work without any change on xterm.js?

**Comment by richarddavenport** [comment] 2016-07-20 15:31
@parisk Yes, it is working without any change to xterm.js.

**Comment by apjanke** [comment] 2016-07-20 19:10
> > Maybe the fix is as simple as removing that `if (self.applicationKeypad) return;` check from the mouse scroll wheel handler.
> @apjanke this won't work and should not work actually. This particular event handler is there to allow scrolling in simple text mode applications like bash, which have `applicationKeypad` set to false (btw. sounds quite helpful to document this better).

Shouldn't this behavior be just a function of the mouse tracking mode, Alternate Screen, and Alternate Scroll modes, and not the numeric/cursor Application Keypad modes? OP is using `zsh`, which is more like `bash` than like `vim`: it's a simple text application that uses the main screen and which does not provide its own scrolling support, so it relies on the terminal to do scrolling. But some of those simple text programs, especially `zsh`, might still enable Application Keypad mode so they can do portable key binding using `terminfo` definitions, which typically only include the application mode character sequences.

**Comment by jerch** [comment] 2016-07-21 00:17
@parisk I second that - why should a keyboard mode settings interfere at all with the mouse behavior? The official xterm spec does not mention any of this, therefore implementing an xterm compatible model should not have such a limitation. Do I miss something here?

**Comment by ksnyde** [comment] 2016-07-29 13:24
What's the easiest "work-around" available before this is addressed a more verbose manner?

**Comment by Tyriar** [comment] 2016-07-29 15:41
@ksnyde this is probably the easiest: https://github.com/Microsoft/vscode/issues/7817#issuecomment-229069151. I haven't tried it personally though.

**Comment by apjanke** [comment] 2016-07-29 18:46
> this is probably the easiest: Microsoft/vscode#7817 (comment). I haven't tried it personally though.

Unfortunately, that will break other key bindings which depend on `zle_line_init`. You may or may not use those key bindings, so it may or may not matter to you.

There's an open OMZ PR I put in to [drop the `zle_line_init`/`[sr]mkx` dependency and stick with normal keypad mode](https://github.com/robbyrussell/oh-my-zsh/pull/5113), and which seems likely to be accepted. If you run that locally, or upvote it so it gets merged in to the OMZ mainline, you can use that as a workaround that avoids this scrolling issue (by avoiding application keypad mode altogether) and keeps all OMZ key bindings working.

That is, if you are using Oh My Zsh. If you are using one of the Linux distributions which configure `zle_line_init` to use `[sr]mkx` in their system config files, you'll need to redefine `zle_line_init` in your own `~/.zshrc` config file as a do-nothing.

```
function zle-line-linit() {
  # NOP
}
```

(This may still break other key bindings that depend on application keypad mode.)

**Comment by apjanke** [comment] 2016-07-29 18:59
> For those apps there is no terminal scrolling. You can test this yourself by running vim or emacs in xterm - you can't scroll back to previous terminal content.

Minor difference, but this is not quite true: in xterm, at least some versions of it, if you run `vim`, it switches to the alternate screen, but you can still scroll back and see earlier contents of the buffer (as long as the buffer has more than a screen of content), as long as you have not enabled mouse event handling in `vim`. If you `:set mouse=a` in `vim`, then it will receive mouse events, and the terminal will not scroll in response to them. Most users probably don't see the former behavior because they have their `.vimrc` set up to automatically enable mouse event handling. I think this suggests that the terminal-level widget scrolling behavior is controlled by mouse event handling, not by the alternate screen mode.

**Comment by jerch** [comment] 2016-08-08 09:13
Thanks for clarification @apjanke - to fully mimick xterm's behavior the handling of the scroll buffer and DECSET has to be reviewed first IMO.

**Comment by ayapi** [comment] 2016-08-20 06:23
@Tyriar , please teach me why 1b886a44 is needed.
you just want to hide a vertical scrollbar?
i observed xterm's behavior on linux for a little while, i thought that 1b886a44 should be dropped.

**Comment by Tyriar** [comment] 2016-09-25 09:28
@ayapi that commit is being reverted in https://github.com/sourcelair/xterm.js/pull/287

I don't think it will help this problem though, the scroll bar will still be disabled in oh my zsh.

**Comment by apjanke** [comment] 2016-09-25 11:01
FWIW, I think this is a case of Xterm.js deviating from normal xterm behavior, and is not Oh My Zsh's problem, and this bug should be closed. If OMZ does provide a compatibility shim for it, it should be confined to a plugin.

**Comment by Tyriar** [comment] 2016-09-25 11:18
@apjanke so you agree with the PR I just put up? #289

**Closed** 2016-09-25 11:44 UTC
Labels: bug

**Comment by apjanke** [comment] 2016-09-25 13:04
Yes, I agree with https://github.com/sourcelair/xterm.js/pull/289. "Application mode" as discussed here is just a keypad mode switch; mouse behavior should be unaffected by it, so wheel events should be allowed.
