### ISSUE TITLE
Copy & paste

### ISSUE THREAD

**Issue by PhilippeAssis** [sourcelair/xterm.js#185] opened 2016-07-14 00:38 UTC
To paste is CTRL + SHIFT + V Ok.
But how to copy ?!

**Comment by Tyriar** [comment] 2016-07-14 05:38
Only <kbd>ctrl</kbd>+<kbd>ins</kbd> copies text currently.

This is a duplicate of https://github.com/sourcelair/xterm.js/issues/118

**Closed** 2016-07-20 09:16 UTC

**Comment by mquinson** [comment] 2019-06-14 00:55
For the record, Shift + Ins can be used to paste text.
