### ISSUE TITLE
Line Wrapping

### ISSUE THREAD

**Issue by BenHall** [sourcelair/xterm.js#204] opened 2016-07-22 14:50 UTC
When entering long commands, the line wraps and cuts off. This makes it harder to read and update what's happening. With iTerm etc it wraps onto a second line.

Is it possible to have it wrapping onto a second line instead of overriding?

**Comment by jerch** [comment] 2016-07-22 17:14
Thanks @BenHall. This is most likely a duplicate of #171.

**Closed** 2016-09-06 13:47 UTC
