### ISSUE TITLE
odd copy behavior inside curses applications

### ISSUE THREAD

**Issue by ricktbaker** [sourcelair/xterm.js#1049] opened 2017-10-11 02:59 UTC
I'm using a combination of electron, xterm.js and node-pty on a mac. Normal copying works fine if I cat a file out, or just try and copy some terminal text. But when I try and copy some text while using vi or top, it copies something completely different.  

Example:  I fire up vim and copy the first line of what I'm editing, it will actually copy the 1st line of my terminal session instead.

## Details
- Browser and browser version: electron 1.7.8
- OS version: Mac 10.12.6
- xterm.js version: 2.9.2

### Steps to reproduce

1. open an xterm window
2. fork a node-pty process
3. Redirect node-pty output to xterm
4. Fire up vim and edit a file
5. Copy some text - note the text being copied isn't from the file being edited but from the original terminal buffer.

**Comment by mofux** [comment] 2017-10-11 14:31
I can reproduce this bug in the current master, but it is fixed in the v3 branch. Since we will release the v3 branch in a month from now, I will not try to back port a fix into current master.

**Closed by mofux** 2017-10-11 14:31 UTC

**Comment by ricktbaker** [comment] 2017-10-11 14:40
Thanks @mofux.  Do you know when this bug was introduced?  If so I can just downgrade my version until then to one that doesn't have this behavior.

**Comment by mofux** [comment] 2017-10-11 19:38
Not sure, between 2.8 and 2.9 we changed some of the buffer related stuff, maybe you could try 2.8 or 2.7 and see if the bug wasn't in there 🤔

**Comment by Tyriar** [comment] 2017-10-28 09:01
Yeah this was fixed in the v3 branch

**Comment by albinekb** [comment] 2017-12-06 19:44
@Tyriar do you think it's an easy fix? We're using xterm 2.9.x in hyper and are running in to this issue. I'm not familiar with the xterm code base but could do some digging if you think it's worth it. 

What would you do? I see VS Code is already using 3.x so I don't know if it's worth investigating or if we'll switch to 3 before releasing hyper 2.0...
