### ISSUE TITLE
How to get input commands

### ISSUE THREAD

**Issue by smalltimoo** [sourcelair/xterm.js#617] opened 2017-03-23 06:36 UTC
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. How to get input commands
For example: I enter a command in xterm.js, how do I get this command
2.

**Comment by akalipetis** [comment] 2017-03-23 07:22
Hello @smalltimoo - could you please explain a bit more what do you mean? How do you enter an input command?

If, for example, you run a command in your terminal that requires user input, this will just work, there's no action you need to take.

**Comment by Tyriar** [comment] 2017-03-23 20:26
Unfortunately this is not as easy as it would seem, as the input is passed to the shell and there's no way to differentiate whether it's a command or input. There are some techniques that can be used such as wrapping the shell process or implementing something like iTerm2's shell integration https://github.com/sourcelair/xterm.js/issues/576. I'm closing this as a duplicate of that since that seems like the best way forward at the moment.

**Closed by Tyriar** 2017-03-23 20:26 UTC
Labels: question

**Comment by smalltimoo** [comment] 2017-03-24 08:10
I entered a command on terminal, and I want to get this command when I press the Enter key

**Comment by Tyriar** [comment] 2017-03-24 17:12
@smalltimoo you can try listening to the key events yourself, otherwise https://github.com/sourcelair/xterm.js/issues/617#issuecomment-288849502 explains the current situation.

**Comment by smalltimoo** [comment] 2024-09-24 13:23
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
