### ISSUE TITLE
Wrong restore a cursor position in Midnight Commander

### ISSUE THREAD

**Issue by meefik** [sourcelair/xterm.js#229] opened 2016-08-14 15:15 UTC
Midnight Commander send two command for save a cursor positon:
1. ESC 7 (DECSC)
   https://github.com/sourcelair/xterm.js/blob/b32a34b97c71539d86c5df5871b40397dc04fcf0/src/xterm.js#L2052
   xterm.js received a position X and Y correctly.
2. CSI s (ANSI.SYS)
   https://github.com/sourcelair/xterm.js/blob/b32a34b97c71539d86c5df5871b40397dc04fcf0/src/xterm.js#L2430
   xterm.js received a position X and Y always 0.
## Details
- Browser and browser version: Google Chrome 52.0.2743.116 (64-bit)
- OS version: Debian 8
- xterm.js version: b32a34b97c71539d86c5df5871b40397dc04fcf0
### Steps to reproduce
1. Run demo app.
2. Execute command mc.
3. Exit from mc.
4. Cursor restored always x:0, y:0.

**Comment by parisk** [comment] 2016-08-17 10:31
Are there any chances that this got fixed after #231?

**Comment by meefik** [comment] 2016-08-17 10:43
No, it is not associated. I fixed this, comment out the two lines:
https://github.com/sourcelair/xterm.js/blob/b32a34b97c71539d86c5df5871b40397dc04fcf0/src/xterm.js#L2430
https://github.com/sourcelair/xterm.js/blob/b32a34b97c71539d86c5df5871b40397dc04fcf0/src/xterm.js#L2436
But I don't know what impact these changes will have.

**Comment by Santinell** [comment] 2016-09-30 06:24
I have the same problem, but meefik's workaround don't work for me...
xterm.js version: 1.1.3

**Comment by Santinell** [comment] 2016-09-30 12:27
Works for me when this line is commented out:
https://github.com/sourcelair/xterm.js/blob/b32a34b97c71539d86c5df5871b40397dc04fcf0/src/xterm.js#L2068

**Comment by AndrienkoAleksandr** [comment] 2017-02-15 20:33
This is bug is depends on Midnight Commander version. For example for MC 4.8.15 this bug is reproducible; mc 4.8.18 - works without this issue.

**Comment by AndrienkoAleksandr** [comment] 2017-02-15 21:00
@parisk https://github.com/sourcelair/xterm.js/pull/231 didn't fix this issue, because this is bug of the text user interface parser(we need improve this parser - InputHandler.ts).

**Comment by Tyriar** [comment] 2017-02-15 21:39
If this only repros in an older version of MC then they probably fixed the issue on their end? The logic for save and restore cursors seems pretty foolproof to me:

```ts
  /**
   * CSI s
   *   Save cursor (ANSI.SYS).
   */
  public saveCursor(params: number[]): void {
    this._terminal.savedX = this._terminal.x;
    this._terminal.savedY = this._terminal.y;
  }


  /**
   * CSI u
   *   Restore cursor (ANSI.SYS).
   */
  public restoreCursor(params: number[]): void {
    this._terminal.x = this._terminal.savedX || 0;
    this._terminal.y = this._terminal.savedY || 0;
  }
```

**Comment by Santinell** [comment] 2017-02-16 05:03
Unfortunately in Ubuntu 16.04 you can install only 4.8.15 from official repos.
For Ubuntu 14.04 version of MC is much older I think

**Comment by Tyriar** [comment] 2017-07-04 14:51
Fixed in https://github.com/sourcelair/xterm.js/pull/728

**Closed by Tyriar** 2017-07-04 14:51 UTC
