### ISSUE TITLE
demo Can't work after browser F5 refresh

### ISSUE THREAD

**Issue by linshijian** [sourcelair/xterm.js#567] opened 2017-02-24 04:06 UTC
Details

Browser and browser version: chrome 55
OS version: Windows 10

Steps to reproduce

after first run “npm start”, the demo can work,
but after refresh the browser，the demo is bad.

how can i to use it  correctly.

**Comment by parisk** [comment] 2017-03-02 09:01
@linshijian xterm.js works fine after refreshing for me on MacOS Chrome 56.

Can you please try running this in an incognito window (Ctrl + Shift + N) and see how it goes (Chrome extensions might be messing up with refreshes).

Also, please share any console logs you get, as they might indicate an error.

**Comment by Tyriar** [comment] 2017-03-03 06:06
I have seen this issue, it's Windows-specific and related to the terminal session/socket dying when the demo is refreshed.

**Comment by mofux** [comment] 2017-03-03 09:17
It also happens to me on my Mac

On 3 Mar 2017, at 07:06, Daniel Imms <notifications@github.com<mailto:notifications@github.com>> wrote:


I have seen this issue, it's Windows-specific and related to the terminal session/socket dying when the demo is refreshed.

**Comment by Tyriar** [comment] 2017-03-03 16:43
@mofux oh really? I haven't seen that.

**Comment by Tyriar** [comment] 2017-03-03 22:39
Fixed in https://github.com/sourcelair/xterm.js/pull/584

@mofux if you repro for osx again please file a new issue, this should fix the Windows problem.

**Closed by Tyriar** 2017-03-03 22:39 UTC
Labels: bug

**Comment by mofux** [comment] 2017-03-04 10:01
@Tyriar Can't reproduce anymore on OSX, sorry for the hassle
