### ISSUE TITLE
Context menu doesn't have copy paste in firefox

### ISSUE THREAD

**Issue by ManojkumarV** [sourcelair/xterm.js#340] opened 2016-11-04 10:03 UTC
Browser context menu in chrome have copy paste options. But in firefox it doesn't have copy paste option.

**Comment by ManojkumarV** [comment] 2016-11-04 10:07
Difference between chrome and firefox in context menu

<img width="1015" alt="chrome" src="https://cloud.githubusercontent.com/assets/10399151/20001999/97cfc710-a2a4-11e6-93b4-9fb8ef5a77b6.png">
<img width="966" alt="firefox" src="https://cloud.githubusercontent.com/assets/10399151/20002000/99a61a30-a2a4-11e6-9107-87e42dcb09ac.png">

**Comment by parisk** [comment] 2016-11-04 10:31
Thanks for reporting @ManojkumarV. I am closing this as it seems to be a duplicate of #310 which you can follow.

**Closed** 2016-11-04 10:31 UTC
