### ISSUE TITLE
Clicking / dragging scroll bar doesn't scroll 

### ISSUE THREAD

**Issue by aashidham** [sourcelair/xterm.js#590] opened 2017-03-09 00:33 UTC
xterm.js pops open a scroll bar, but you can't click it / drag it anywhere. How do I fix this?

## Details
- Browser and browser version: Chrome 
- OS version: OSX 10.9.5

**Comment by aashidham** [comment] 2017-03-11 19:23
ping?

**Comment by vincentwoo** [comment] 2017-03-13 00:21
perhaps dupe of #512

**Comment by aashidham** [comment] 2017-03-13 02:29
Was this ever resolved?

**Comment by parisk** [comment] 2017-03-13 07:01
Scrollbar works great for me on the demo on Chrome 56.

Did this happen on the demo for you?

**Comment by Tyriar** [comment] 2017-03-13 18:58
Yes this looks like a duplicate of https://github.com/sourcelair/xterm.js/issues/512

**Closed by Tyriar** 2017-03-13 18:58 UTC
