### ISSUE TITLE
Line Spacing Issues

### ISSUE THREAD

**Issue by uudruid74** [sourcelair/xterm.js#475] opened 2017-01-13 09:01 UTC
There are some odd line spacing issues.  The line spacing is set at 21px in the demo, but this makes spaces between the lines.  Setting it to 18px will get rid of the spaces, but now mouse coordinates are all off since they are based on the 21px line height.  Worse, some apps (like htop - see screenshot) display the status bar half-over the bottom of the terminal.   I think these are related.

## Details
- Chrome 53
- OS version: Antergos(Arch) Linux 
- xterm.js version: git ... 2.2.3-99-gfc528f6

Here's HTOP hanging over the edge
![screenshot from 2017-01-13 02-17-13](https://cloud.githubusercontent.com/assets/7726301/21923811/c57fc08e-d93b-11e6-9a78-9c003deb7562.png)

Here is Midnight Commander looking awful (spaces between lines):
![screenshot from 2017-01-13 02-44-36](https://cloud.githubusercontent.com/assets/7726301/21923865/047e0e08-d93c-11e6-8e72-3c42525cfad4.png)

And the expected behavior of Midnight Commander (shown in shellinabox, colors set to linux terminal):
![screenshot from 2017-01-13 02-44-59](https://cloud.githubusercontent.com/assets/7726301/21923885/229c5dfe-d93c-11e6-9121-d3db0f478248.png)

**Comment by uudruid74** [comment] 2017-01-13 09:11
After pulling down some menu items, you'll notice that some lines get "out of sync" with the ones next to them and the statusbar line starts creeping lower on the screen, spilling over like the HTOP display.   TMUX will eventually do the same and have a statusbar way below the actual terminal screen.   The mouse support of xterm.js is a lot bettter than shellinabox though!

![screenshot from 2017-01-13 03-08-39](https://cloud.githubusercontent.com/assets/7726301/21924234/e91304e6-d93d-11e6-942b-2a0b5628ef34.png)

**Comment by Tyriar** [comment] 2017-01-13 17:26
Which commit is this on? https://github.com/sourcelair/xterm.js/commits/master

**Comment by parisk** [comment] 2017-01-16 12:51
@uudruid74 can you confirm if this happens on master?

**Comment by uudruid74** [comment] 2017-01-17 15:49
ekl@Taro ~/Programming/xterm.js/demo (git)-[master] % git describe
0.31-615-gfc528f6

**Comment by Tyriar** [comment] 2017-01-17 19:10
I can't repro these line spacing issues on Windows, Mac or Linux on the demo. Do you have any other CSS on the page that could affect this?

I also recommend checking on the latest `master` since your commit seems a little out of date.

**Comment by uudruid74** [comment] 2017-01-19 05:07
This is just running the installed demo - no changes whatsoever.  Linux Chrome 53 and running demo via localhost.

> xterm@2.2.3 start /home/ekl/Programming/xterm.js
> node demo/app

ekl@Taro ~/Programming/xterm.js (git)-[master] % git describe                                :(
0.31-670-g5bd8033

Still the same!

FIX:  I changed the fonts being used by adding the following to the stylesheet.

`font-family: "DejaVu Sans Mono", "Everson Mono", FreeMono, "Andale Mono", monospace;`

It's the set I use with shell-in-a-box, so apparently courier is suspect on this system.   I think on some systems, Courier looks monospace, but actually isn't.

**Comment by wayerr** [comment] 2017-03-22 12:01
I found same issue, it appeared on debian linux in ff 52.0.1, but not exists in cromium 57.0.2987.98 on same os. See attached screen shot:
![spectacle tj8462](https://cloud.githubusercontent.com/assets/3847021/24196723/f2608d54-0f0f-11e7-9eb8-42d476b5663d.png)
Browsers choose different fonts (it strange) and different line height .

**Comment by wayerr** [comment] 2017-03-22 13:56
Explanation show that 'line' span-s (which act as background color) has height 16px
![screenshot_20170322_165429](https://cloud.githubusercontent.com/assets/3847021/24201141/3faeceb2-0f20-11e7-934f-987967de5277.png)
when must have 17px, it may be fixed by additional css: 
```
.xterm-rows span {
    display: inline-block;
}
```
but i`m not sure that is right way.

**Comment by mofux** [comment] 2017-03-22 14:07
I can reproduce the problem above, and @wayerr solution seems to work very well, as it does not change the height of the surrounding div. I guess the only problem with using `inline-block` vs `inline` would be the wrapping behaviour on text overflow, but that should actually never happen.

**Closed** 2017-09-08 18:08 UTC
Labels: bug
