### ISSUE TITLE
Clear selection after terminal range is cleared

### ISSUE THREAD

**Issue by ManojkumarV** [sourcelair/xterm.js#806] opened 2017-07-19 07:17 UTC
Select a range of text in the terminal. Now press ctrl+L to clear the terminal text. The selected range will get retained in the empty area. Is there any way to clear selection when terminal range is cleared?

**Comment by Tyriar** [comment] 2017-07-19 15:19
Duplicate of https://github.com/sourcelair/xterm.js/issues/777 should be fixed in master

**Closed by Tyriar** 2017-07-19 15:19 UTC
